version: "3.1"

services:
  db:
    image: postgres:14.2-alpine
    restart: always
    container_name: api-golang-mvc
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: api-golang
      POSTGRES_DB: api-golang
    ports:
      - "5432:5432"

    volumes:
      - ./database/data:/var/lib/postgresql/data
